"""
STEP 11 — Collect everything the manuscript needs
==================================================

Reads the outputs of steps 05–10 for every cell of the experimental matrix
and writes results/paper/:

  table1_dataset.{csv,md}            per panel / scheme / side: n, genes, class balance
  table2_main_results.{csv,md}       ROC-AUC (95 % CI) per panel × (scheme, feature set)
  table3_circularity.{csv,md}        type-1 effect: full − core (paired DeLong, same test set)
                                     type-2 effect: variant − gene (independent test sets)
  table4_track_c_ablation.{csv,md}   A vs A+C per panel and run
  table5_baselines.{csv,md}          published predictors vs our models
  table6_features.{csv,md}           feature counts per group per run
  figures/                           copies of the key figures with stable names
  summary.md                         all tables in one document
  provenance.json                    environment + config + data provenance per run
"""

from __future__ import annotations

import os
import json
import glob
import shutil
import argparse
import numpy as np
import pandas as pd

from utils.logging_utils import get_logger
from utils.config import load_config, run_dir
from utils.schema import TARGET_COL
from utils.metrics import delong_roc_test, paired_bootstrap_auc_diff

log = get_logger("11_paper_tables.log")


def fmt_ci(a, lo, hi):
    return f"{a:.3f} ({lo:.3f}–{hi:.3f})"


def to_md(df: pd.DataFrame) -> str:
    try:
        return df.to_markdown(index=False, floatfmt=".3f")
    except Exception:                      # tabulate not installed
        cols = list(df.columns)
        lines = ["| " + " | ".join(cols) + " |", "|" + "---|" * len(cols)]
        for _, r in df.iterrows():
            lines.append("| " + " | ".join(f"{v:.3f}" if isinstance(v, float) else str(v) for v in r) + " |")
        return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--config", default="config/pipeline.yaml")
    ap.add_argument("--fast", action="store_true")
    args = ap.parse_args()
    cfg = load_config(args.config)
    SEED = int(cfg["seed"]); PANELS = cfg["panels"]
    N_BOOT = 200 if args.fast else int(cfg["model"]["n_bootstrap"])
    out = os.path.join(cfg["paths"]["results"], "paper")
    os.makedirs(os.path.join(out, "figures"), exist_ok=True)
    md = ["# NeuroVariant — result tables (auto-generated by scripts/11_paper_tables.py)\n"]

    # ── Table 1: dataset ─────────────────────────────────────────────────
    ds_path = os.path.join(cfg["paths"]["final"], "dataset_summary.csv")
    if os.path.exists(ds_path):
        t1 = pd.read_csv(ds_path)
        t1.to_csv(os.path.join(out, "table1_dataset.csv"), index=False)
        md += ["## Table 1 — Datasets\n", to_md(t1), ""]

    # ── Table 2: main results ────────────────────────────────────────────
    runs = {}
    for scheme in cfg["split_schemes"]:
        for fset in cfg["feature_sets"]:
            rd = run_dir(cfg, scheme, fset)
            if os.path.exists(os.path.join(rd, "results_table.csv")):
                runs[(scheme, fset)] = rd
    rows = []
    for (scheme, fset), rd in runs.items():
        rt = pd.read_csv(os.path.join(rd, "results_table.csv"))
        meta_path = os.path.join(rd, "meta", "meta_ablation_table.csv")
        mt = pd.read_csv(meta_path).set_index("panel") if os.path.exists(meta_path) else None
        for _, r in rt.iterrows():
            rows.append({"scheme": scheme, "feature_set": fset, "panel": r["panel"], "n_test": int(r["n"]),
                         "n_test_genes": int(r["n_genes"]), "roc_auc": r["roc_auc"],
                         "roc_auc_ci": fmt_ci(r["roc_auc"], r["roc_auc_lo"], r["roc_auc_hi"]),
                         "pr_auc": r["pr_auc"], "f1_youden": r["f1_youden"], "sens_youden": r["sens_youden"],
                         "spec_youden": r["spec_youden"], "mcc": r["mcc_youden"], "brier": r["brier"],
                         "sens_at_sens90": r["sens_sens90"], "spec_at_sens90": r["spec_sens90"],
                         "auc_meta": float(mt.loc[r["panel"], "auc_meta"]) if mt is not None else np.nan})
    t2 = pd.DataFrame(rows)
    if len(t2):
        t2.to_csv(os.path.join(out, "table2_main_results.csv"), index=False)
        piv = t2.pivot_table(index="panel", columns=["scheme", "feature_set"], values="roc_auc_ci", aggfunc="first")
        piv.columns = [f"{s}/{f}" for s, f in piv.columns]
        md += ["## Table 2 — ROC-AUC (95 % bootstrap CI), Track A, Youden threshold\n", to_md(piv.reset_index()), ""]

    # ── Table 3: circularity effects ─────────────────────────────────────
    t3 = []
    for scheme in cfg["split_schemes"]:                      # type-1: full vs core, same test rows
        a, b = runs.get((scheme, "core")), runs.get((scheme, "full"))
        if a and b:
            for p in PANELS:
                pa = pd.read_csv(os.path.join(a, f"predictions_{p}.csv"))
                pb = pd.read_csv(os.path.join(b, f"predictions_{p}.csv"))
                d = pa.merge(pb, on="_variant_id", suffixes=("_core", "_full"))
                y = d[f"{TARGET_COL}_core"].astype(int).values
                if len(np.unique(y)) < 2:
                    continue
                dl = delong_roc_test(y, d["P_pathogenic_full"], d["P_pathogenic_core"])
                bs = paired_bootstrap_auc_diff(y, d["P_pathogenic_full"], d["P_pathogenic_core"], n_boot=N_BOOT, seed=SEED)
                t3.append({"effect": "type-1 (in-silico features): full − core", "scheme": scheme, "panel": p,
                           "n": len(y), "auc_a": dl["auc1"], "auc_b": dl["auc2"], "delta": dl["delta"],
                           "ci_lo": bs["ci"][0], "ci_hi": bs["ci"][1], "p_delong": dl["p"], "paired": True})
    for fset in cfg["feature_sets"]:                          # type-2: variant vs gene, different test sets
        a, b = runs.get(("variant", fset)), runs.get(("gene", fset))
        if a and b:
            ra = pd.read_csv(os.path.join(a, "results_table.csv")).set_index("panel")
            rb = pd.read_csv(os.path.join(b, "results_table.csv")).set_index("panel")
            for p in PANELS:
                if p in ra.index and p in rb.index:
                    lo = ra.loc[p, "roc_auc_lo"] - rb.loc[p, "roc_auc_hi"]
                    hi = ra.loc[p, "roc_auc_hi"] - rb.loc[p, "roc_auc_lo"]
                    t3.append({"effect": "type-2 (gene leakage): variant − gene", "scheme": fset, "panel": p,
                               "n": int(ra.loc[p, "n"]), "auc_a": ra.loc[p, "roc_auc"], "auc_b": rb.loc[p, "roc_auc"],
                               "delta": ra.loc[p, "roc_auc"] - rb.loc[p, "roc_auc"], "ci_lo": lo, "ci_hi": hi,
                               "p_delong": np.nan, "paired": False})
    if t3:
        t3 = pd.DataFrame(t3)
        t3.to_csv(os.path.join(out, "table3_circularity.csv"), index=False)
        md += ["## Table 3 — Circularity effects on ROC-AUC\n",
               "type-1 rows: paired DeLong on identical test variants. type-2 rows: independent test sets; "
               "CI shown is the conservative difference of the two 95 % CIs.\n", to_md(t3), ""]

    # ── Table 4: Track C ablation ────────────────────────────────────────
    t4 = []
    for (scheme, fset), rd in runs.items():
        mp = os.path.join(rd, "meta", "meta_ablation_table.csv")
        if os.path.exists(mp):
            t4.append(pd.read_csv(mp).assign(scheme=scheme, feature_set=fset))
    if t4:
        t4 = pd.concat(t4, ignore_index=True)
        t4.to_csv(os.path.join(out, "table4_track_c_ablation.csv"), index=False)
        md += ["## Table 4 — Track C (rule prior) ablation: Track A vs stacked A+C\n", to_md(t4), ""]

    # ── Table 5: baselines ───────────────────────────────────────────────
    t5 = []
    for scheme in cfg["split_schemes"]:
        bp = os.path.join(cfg["paths"]["results"], f"{scheme}_baselines", "comparisons_table.csv")
        if os.path.exists(bp):
            t5.append(pd.read_csv(bp).assign(scheme=scheme))
    if t5:
        t5 = pd.concat(t5, ignore_index=True)
        t5.to_csv(os.path.join(out, "table5_baselines.csv"), index=False)
        md += ["## Table 5 — Published predictors vs NeuroVariant (same variants, DeLong)\n", to_md(t5), ""]

    # ── Table 6: features per group ──────────────────────────────────────
    t6 = []
    for (scheme, fset), rd in runs.items():
        fc = json.load(open(os.path.join(rd, "feature_cols.json")))
        row = {"scheme": scheme, "feature_set": fset, "n_features": len(fc["feature_cols"])}
        row.update({g: len(c) for g, c in fc["groups"].items()})
        t6.append(row)
    if t6:
        t6 = pd.DataFrame(t6).fillna(0)
        t6.to_csv(os.path.join(out, "table6_features.csv"), index=False)
        md += ["## Table 6 — Features retained per group\n", to_md(t6), ""]

    # ── Figures + provenance ─────────────────────────────────────────────
    for (scheme, fset), rd in runs.items():
        for f in glob.glob(os.path.join(rd, "figures", "*.png")):
            shutil.copy(f, os.path.join(out, "figures", f"{scheme}_{fset}_{os.path.basename(f)}"))
    for scheme in cfg["split_schemes"]:
        for f in glob.glob(os.path.join(cfg["paths"]["results"], f"{scheme}_baselines", "figures", "*.png")):
            shutil.copy(f, os.path.join(out, "figures", os.path.basename(f)))
    prov = {"runs": {}, "data_provenance": {}}
    for (scheme, fset), rd in runs.items():
        prov["runs"][f"{scheme}_{fset}"] = {k: json.load(open(os.path.join(rd, f"{k}.json")))
                                            for k in ("environment", "run_config") if os.path.exists(os.path.join(rd, f"{k}.json"))}
    for f in glob.glob("data/raw/provenance_*.json"):
        prov["data_provenance"][os.path.basename(f)] = json.load(open(f))
    with open(os.path.join(out, "provenance.json"), "w") as f:
        json.dump(prov, f, indent=2, default=str)
    with open(os.path.join(out, "summary.md"), "w") as f:
        f.write("\n".join(md))
    log.info(f"✓ paper tables → {out}  ({len(runs)} runs found)")


if __name__ == "__main__":
    main()
